export const environment = {
    API_endpoints:{
        userAccount:"https://localhost:7119/UserAccount/GetAll",
        updateUserStatus:`https://localhost:7119/UserAccount/`,
        educationalDetails:"https://localhost:7119/EducationalDetails/Get/",
        login:"https://localhost:7119/Auth/Login",
        resetPassword:"https://localhost:7119/UserAccount/ResetPassword",
        experienceDetails:"https://localhost:7119/ExperienceDetails/Get/",
        jobSeekerProfile:"https://localhost:7119/SeekerProfile/Get/",
        jobPosts:"https://localhost:7119/JobPost/Get/",
        deleteUser:"https://localhost:7119/UserAccount/DeleteAccount",
        applyJob:"https://localhost:7119/JobPostActivity/ApplyToJobPost",
        company:"https://localhost:7119/Company/GetAll",
        createJob:"https://localhost:7119/JobPost/CreateJobPost",
        location:"https://localhost:7119/JobLocation/GetAll",
        jobById:"https://localhost:7119/JobPost/GetById/",
        deleteJob:"https://localhost:7119/JobPost/DeleteJobPost/",
        appliedJobs:"https://localhost:7119/JobPostActivity/GetById/"
    }
};
